[pytest]
addopts = -s -v
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    authentication: Маркировка для тестов, связанных с аутентификацией.
    courses: Маркировка для тестов, связанных с курсами.
    exercises: Маркировка для тестов, связанных с заданиями.
    files: Маркировка для тестов, связанных с файлами.
    users: Маркировка для тестов, связанных с пользователями.
    regression: Маркировка для регрессионных тестов.